name: CI
on: [push]
jobs:
  test:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm install

      - name: compile
        run: npm run compile

      - name: test
        run: npm run test
